problem:
  name: dengue_prediction
  problem_type: regression
  problem_type_details:
    scorer: neg_mean_absolute_error
    classification_type:

data:
  s3_bucket: mit-dai-micahs-misc
  s3_bucket_region: us-east-1
  train: data/raw
  entities_table_name: dengue_features
  target_table_name: dengue_labels

contrib:
  module_name: dengue_prediction.features.contrib
  module_path: dengue_prediction/features/contrib
  comparison_remote: origin
  comparison_ref: master

tables:
  -
    name: dengue_features
    path: dengue_features.csv
    pd_read_kwargs:
      index_col:
      - city
      - year
      - weekofyear
      header: 0
  -
    name: dengue_labels
    path: dengue_labels.csv
    pd_read_kwargs:
      index_col:
      - city
      - year
      - weekofyear
      header: 0
