problem:
  name: dengue_prediction
  problem_type: regression
  problem_type_details:
    # either
    # - sklearn string http://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
    # - function name, such as dengue_prediction.models.scoring.scorer using make_scorer
    scorer: neg_mean_absolute_error
    classification_type:
  data:
    train: 'data/raw'
    entities_table_name: dengue_features
    target_table_name: dengue_labels
  reference_remote: origin
  reference_branch: master

tables:
  -
    name: dengue_features
    path: dengue_features.csv
    pd_read_kwargs:
      index_col:
      - city
      - year
      - weekofyear
      header: 0
  -
    name: dengue_labels
    path: dengue_labels.csv
    pd_read_kwargs:
      index_col:
      - city
      - year
      - weekofyear
      header: 0
